/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author enzog
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivos = new javax.swing.JMenu();
        mnArquivosClientes = new javax.swing.JMenuItem();
        mnArquivosProdutos = new javax.swing.JMenuItem();
        mnArquivosUsuários = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnArquivosAltSenha = new javax.swing.JMenuItem();
        mnArquivosAltUsuário = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnArquivosSair = new javax.swing.JMenuItem();
        mnMovimentos = new javax.swing.JMenu();
        mnMovimentosVendas = new javax.swing.JMenuItem();
        mnMovimentosRelVendas = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mnAjudaSobre = new javax.swing.JMenuItem();
        mnAjudaAjude = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de pedidos");

        mnArquivos.setText("Arquivos");

        mnArquivosClientes.setText("Clientes");
        mnArquivos.add(mnArquivosClientes);

        mnArquivosProdutos.setText("Produtos");
        mnArquivos.add(mnArquivosProdutos);

        mnArquivosUsuários.setText("Usuários");
        mnArquivos.add(mnArquivosUsuários);
        mnArquivos.add(jSeparator1);

        mnArquivosAltSenha.setText("Alterar senha");
        mnArquivos.add(mnArquivosAltSenha);

        mnArquivosAltUsuário.setText("Alterar usuário");
        mnArquivos.add(mnArquivosAltUsuário);
        mnArquivos.add(jSeparator2);

        mnArquivosSair.setText("Sair");
        mnArquivos.add(mnArquivosSair);

        jMenuBar1.add(mnArquivos);

        mnMovimentos.setText("Movimentos");

        mnMovimentosVendas.setText("Vendas");
        mnMovimentos.add(mnMovimentosVendas);

        mnMovimentosRelVendas.setText("Relatórios vendas");
        mnMovimentos.add(mnMovimentosRelVendas);

        jMenuBar1.add(mnMovimentos);

        mnAjuda.setText("Ajuda");

        mnAjudaSobre.setText("Sobre");
        mnAjuda.add(mnAjudaSobre);

        mnAjudaAjude.setText("Ajude-me");
        mnAjuda.add(mnAjudaAjude);

        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenuItem mnAjudaAjude;
    private javax.swing.JMenuItem mnAjudaSobre;
    private javax.swing.JMenu mnArquivos;
    private javax.swing.JMenuItem mnArquivosAltSenha;
    private javax.swing.JMenuItem mnArquivosAltUsuário;
    private javax.swing.JMenuItem mnArquivosClientes;
    private javax.swing.JMenuItem mnArquivosProdutos;
    private javax.swing.JMenuItem mnArquivosSair;
    private javax.swing.JMenuItem mnArquivosUsuários;
    private javax.swing.JMenu mnMovimentos;
    private javax.swing.JMenuItem mnMovimentosRelVendas;
    private javax.swing.JMenuItem mnMovimentosVendas;
    // End of variables declaration//GEN-END:variables
}
