/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import classes.Dados;

/**
 *
 * @author enzog
 */
public class frmMenu extends javax.swing.JFrame {

    private Dados clsdados;
    public void setDados(Dados clsDados) {
        this.clsdados = clsDados;
    }
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivos = new javax.swing.JMenu();
        mnArquivosClientes = new javax.swing.JMenuItem();
        mnArquivosProdutos = new javax.swing.JMenuItem();
        mnArquivosUsuários = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnArquivosAltSenha = new javax.swing.JMenuItem();
        mnArquivosAltUsuário = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnArquivosSair = new javax.swing.JMenuItem();
        mnMovimentos = new javax.swing.JMenu();
        mnMovimentosVendas = new javax.swing.JMenuItem();
        mnMovimentosRelVendas = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mnAjudaSobre = new javax.swing.JMenuItem();
        mnAjudaAjude = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de pedidos");

        javax.swing.GroupLayout deskPanelLayout = new javax.swing.GroupLayout(deskPanel);
        deskPanel.setLayout(deskPanelLayout);
        deskPanelLayout.setHorizontalGroup(
            deskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        deskPanelLayout.setVerticalGroup(
            deskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        mnArquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inbox.png"))); // NOI18N
        mnArquivos.setText("Arquivos");

        mnArquivosClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/target.png"))); // NOI18N
        mnArquivosClientes.setText("Clientes");
        mnArquivosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArquivosClientesActionPerformed(evt);
            }
        });
        mnArquivos.add(mnArquivosClientes);

        mnArquivosProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product.png"))); // NOI18N
        mnArquivosProdutos.setText("Produtos");
        mnArquivos.add(mnArquivosProdutos);

        mnArquivosUsuários.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        mnArquivosUsuários.setText("Usuários");
        mnArquivosUsuários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArquivosUsuáriosActionPerformed(evt);
            }
        });
        mnArquivos.add(mnArquivosUsuários);
        mnArquivos.add(jSeparator1);

        mnArquivosAltSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N
        mnArquivosAltSenha.setText("Alterar senha");
        mnArquivos.add(mnArquivosAltSenha);

        mnArquivosAltUsuário.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        mnArquivosAltUsuário.setText("Alterar usuário");
        mnArquivos.add(mnArquivosAltUsuário);
        mnArquivos.add(jSeparator2);

        mnArquivosSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        mnArquivosSair.setText("Sair");
        mnArquivos.add(mnArquivosSair);

        jMenuBar1.add(mnArquivos);

        mnMovimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payment-method.png"))); // NOI18N
        mnMovimentos.setText("Movimentos");

        mnMovimentosVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        mnMovimentosVendas.setText("Vendas");
        mnMovimentos.add(mnMovimentosVendas);

        mnMovimentosRelVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        mnMovimentosRelVendas.setText("Relatórios vendas");
        mnMovimentos.add(mnMovimentosRelVendas);

        jMenuBar1.add(mnMovimentos);

        mnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        mnAjuda.setText("Ajuda");

        mnAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        mnAjudaSobre.setText("Sobre");
        mnAjuda.add(mnAjudaSobre);

        mnAjudaAjude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        mnAjudaAjude.setText("Ajude-me");
        mnAjuda.add(mnAjudaAjude);

        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnArquivosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArquivosClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnArquivosClientesActionPerformed

    private void mnArquivosUsuáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArquivosUsuáriosActionPerformed
        // TODO add your handling code here:
        frmUsuarios fusuario = new frmUsuarios();
        fusuario.setDados(clsdados);
        deskPanel.add(fusuario);
        fusuario.show();
    }//GEN-LAST:event_mnArquivosUsuáriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenuItem mnAjudaAjude;
    private javax.swing.JMenuItem mnAjudaSobre;
    private javax.swing.JMenu mnArquivos;
    private javax.swing.JMenuItem mnArquivosAltSenha;
    private javax.swing.JMenuItem mnArquivosAltUsuário;
    private javax.swing.JMenuItem mnArquivosClientes;
    private javax.swing.JMenuItem mnArquivosProdutos;
    private javax.swing.JMenuItem mnArquivosSair;
    private javax.swing.JMenuItem mnArquivosUsuários;
    private javax.swing.JMenu mnMovimentos;
    private javax.swing.JMenuItem mnMovimentosRelVendas;
    private javax.swing.JMenuItem mnMovimentosVendas;
    // End of variables declaration//GEN-END:variables
}
